#!/usr/bin/env python3
"""Phase 5 — Capture the committed screenshots of qc-report.html.

`qc-report.html` is gitignored: it is regenerated by one command and embeds a
generation timestamp, so committing it would churn a 34 KB diff every run
(DECISIONS 2026-07-21). The cost is that a prospective client browsing the repo
cannot see the deliverable at all. These screenshots are what pay that cost,
which makes them a REQUIREMENT rather than decoration.

Writes three files:
    docs/qc-report-full.png    the whole report, so nothing looks cherry-picked
    docs/qc-report-hero.png    the summary, readable, for the README header
    docs/report-snapshot.json  the figures the report showed WHEN CAPTURED

The snapshot file is the staleness guard. A screenshot is a photograph of a
number, and photographs do not update themselves — if the pipeline later
produces 26 flagged files, the committed image still says 25 and the repo
starts telling a client something untrue. `qc_phase5.py` re-reads the live
report's `data-qc` figures and compares them against this file, so a drifted
screenshot fails the build instead of quietly misinforming a reader.

Two things are checked here rather than assumed, because both fail silently:
  * the render must be TALLER than the content, otherwise Chrome has cropped
    the bottom off the report and the "whole report" claim is false
  * the hero crop line must land in a gutter, not through a card, otherwise
    the header image shows a sliced-in-half panel

Run:  py scripts/capture_screenshots.py
Requires: qc-report.html (run scripts/run_demo.py first), Chrome, and pillow.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "qc-report.html"
DOCS = ROOT / "docs"
FULL = DOCS / "qc-report-full.png"
HERO = DOCS / "qc-report-hero.png"
SNAPSHOT = DOCS / "report-snapshot.json"

WIDTH = 1100      # the report's own max content width; wider only adds margin
WINDOW_H = 7700   # must exceed the rendered page; verified below, not trusted
MARGIN = 52       # background kept below the last content row
HERO_H = 952      # ends in the gutter under the severity card - verified below

CHROME_CANDIDATES = [
    Path(r"C:\Program Files\Google\Chrome\Application\chrome.exe"),
    Path(r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"),
    Path.home() / r"AppData\Local\Google\Chrome\Application\chrome.exe",
]

# Figures worth pinning: every one is structural (file counts, findings,
# severities, buckets). Deliberately NOT the generation timestamp, which
# changes every run and would make the guard fire on nothing.
PINNED = [
    "total_files", "files_flagged", "files_clean", "total_exceptions",
    "sev_high", "sev_medium", "sev_low",
    "class_labeled", "class_unclassified", "naming_findings",
    "datefid_total", "datefid_ok",
    "files_class", "files_author", "files_custodian",
    "unassigned_class", "unassigned_author", "unassigned_custodian",
    "buckets_class", "buckets_author", "buckets_custodian",
]


def die(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def find_chrome() -> Path:
    for path in CHROME_CANDIDATES:
        if path.is_file():
            return path
    die("Chrome not found. Checked:\n  " +
        "\n  ".join(str(p) for p in CHROME_CANDIDATES))
    raise AssertionError("unreachable")


def report_figures() -> dict[str, str]:
    """Read the data-qc figures out of the rendered report."""
    doc = REPORT.read_text(encoding="utf-8")
    found = dict(re.findall(r'data-qc="([^"]+)">([^<]*)<', doc))
    missing = [k for k in PINNED if k not in found]
    if missing:
        die(f"report is missing expected figures: {', '.join(missing)}")
    return {k: found[k].strip() for k in PINNED}


def last_content_row(im: Image.Image) -> int:
    """The lowest row holding anything other than the page background."""
    px = im.convert("RGB")
    w, h = im.size
    background = px.getpixel((5, h - 5))
    for y in range(h - 1, -1, -1):
        if any(px.getpixel((x, y)) != background for x in range(0, w, 20)):
            return y
    die("the render is entirely background - the report did not draw")
    raise AssertionError("unreachable")


def row_is_background(im: Image.Image, y: int) -> bool:
    px = im.convert("RGB")
    w, h = im.size
    background = px.getpixel((5, h - 5))
    return all(px.getpixel((x, y)) == background for x in range(0, w, 5))


def main() -> int:
    if not REPORT.is_file():
        die(f"{REPORT.name} not found. Run: py scripts/run_demo.py")
    DOCS.mkdir(exist_ok=True)
    chrome = find_chrome()

    url = "file:///" + ROOT.as_posix().lstrip("/") + "/qc-report.html"
    print(f"Rendering {url}\n  at {WIDTH}x{WINDOW_H} via {chrome.name}")
    result = subprocess.run(
        [str(chrome), "--headless=new", "--disable-gpu", "--hide-scrollbars",
         f"--screenshot={FULL}", f"--window-size={WIDTH},{WINDOW_H}", url],
        capture_output=True, text=True)
    if not FULL.is_file():
        die(f"Chrome wrote no screenshot (exit {result.returncode}).\n"
            f"{result.stderr.strip()}")

    with Image.open(FULL) as raw:
        im = raw.copy()
    last = last_content_row(im)
    print(f"  content ends at row {last} of {WINDOW_H}")

    # If content reaches the bottom of the window, the page was taller than the
    # render and the bottom of the report is missing. Never ship that quietly.
    if last >= WINDOW_H - 2:
        die(f"content reaches the bottom of the render ({last}/{WINDOW_H}) - "
            f"the report is being cut off. Raise WINDOW_H and re-run.")

    full = im.crop((0, 0, WIDTH, min(last + MARGIN, WINDOW_H)))
    full.save(FULL)

    if not row_is_background(im, HERO_H - 1):
        die(f"the hero crop line (y={HERO_H}) runs through content, which would "
            f"slice a card in half. Adjust HERO_H to a gutter.")
    im.crop((0, 0, WIDTH, HERO_H)).save(HERO)

    figures = report_figures()
    SNAPSHOT.write_text(json.dumps(
        {"captured_from": REPORT.name,
         "full": {"file": FULL.name, "size": list(full.size)},
         "hero": {"file": HERO.name, "size": [WIDTH, HERO_H]},
         "figures": figures}, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {FULL.relative_to(ROOT)}  {full.size[0]}x{full.size[1]}"
          f"  ({FULL.stat().st_size // 1024} KB)")
    print(f"Wrote {HERO.relative_to(ROOT)}  {WIDTH}x{HERO_H}"
          f"  ({HERO.stat().st_size // 1024} KB)")
    print(f"Wrote {SNAPSHOT.relative_to(ROOT)}  {len(figures)} figures pinned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
